"""
api/routers/dashboard.py — Dashboard chart data and system stats.
"""
import json
import os
from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException
from api.dependencies import get_current_user, require_role
from core.database import get_dashboard_stats, get_feedback_stats

router = APIRouter(prefix="/dashboard", tags=["dashboard"])

CHART_DATA_PATH = Path("output/chart_data.json")


@router.get("/charts")
def get_chart_data(current_user: dict = Depends(get_current_user)):
    """
    Returns chart data from output/chart_data.json (generated by Phase 4).
    Returns a helpful message if the file doesn't exist yet.
    """
    if not CHART_DATA_PATH.exists():
        return {
            "message": "Chart data not found. Run Phase 4 first: python run_phase4.py --no-ragas",
            "data": None,
        }

    try:
        with open(CHART_DATA_PATH) as f:
            data = json.load(f)
        return {"data": data}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read chart data: {str(e)}")


@router.get("/stats")
def get_stats(current_user: dict = Depends(get_current_user)):
    """
    Returns aggregated system stats: documents, chunks, queries, experiments, etc.
    """
    return get_dashboard_stats()


@router.get("/feedback-stats")
def get_feedback_stats_endpoint(
    current_user: dict = Depends(require_role("admin", "researcher")),
):
    """Returns thumbs-up/down counts. Admin and Researcher only."""
    return get_feedback_stats()
