"""
api/routers/query.py — POST /query endpoint: runs the RAG pipeline with role enforcement.
"""
import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from api.dependencies import get_current_user
from api.middleware.rbac import get_role_config

router = APIRouter(prefix="/query", tags=["query"])


class QueryRequest(BaseModel):
    query: str
    session_id: str | None = None
    retriever_type: str = "similarity"
    llm_key: str = "groq-llama8b"
    top_k: int = 5


class ChunkResult(BaseModel):
    rank: int
    score: float
    filename: str
    page_number: int
    preview: str


class QueryResponse(BaseModel):
    query: str
    answer: str
    sources: list
    retriever_type: str
    llm_name: str
    latency_total: float
    cost_usd: float
    record_id: int
    retrieved_chunks: list


def _validate_and_augment(req: QueryRequest, current_user: dict):
    """Shared RBAC validation + query augmentation for both endpoints."""
    role = current_user["role"]
    config = get_role_config(role)

    allowed_llms = config["allowed_llms"]
    if allowed_llms != "all" and req.llm_key not in allowed_llms:
        raise HTTPException(
            status_code=403,
            detail=f"Your role ({role}) cannot use model '{req.llm_key}'. Allowed: {allowed_llms}",
        )

    allowed_retrievers = config["allowed_retrievers"]
    if allowed_retrievers != "all" and req.retriever_type not in allowed_retrievers:
        raise HTTPException(
            status_code=403,
            detail=f"Your role ({role}) cannot use retriever '{req.retriever_type}'. Allowed: {allowed_retrievers}",
        )

    top_k = min(req.top_k, config["max_top_k"])

    complexity = config["response_complexity"]
    if complexity == "simple":
        augmented_query = f"{req.query}\n\n[Respond in plain language, avoid technical jargon.]"
    elif complexity == "detailed":
        augmented_query = f"{req.query}\n\n[Provide a detailed response with references to specific articles.]"
    else:
        augmented_query = f"{req.query}\n\n[Provide a technically precise, expert-level response.]"

    return augmented_query, top_k


@router.post("/", response_model=QueryResponse)
def query(req: QueryRequest, current_user: dict = Depends(get_current_user)):
    """
    Run a RAG query with role-based LLM, retriever, and top_k enforcement.
    """
    from api.main import get_pipeline

    augmented_query, top_k = _validate_and_augment(req, current_user)

    pipeline = get_pipeline()
    if pipeline is None:
        raise HTTPException(status_code=503, detail="Pipeline not initialized")

    try:
        result = pipeline.run_rag_query(
            query=augmented_query,
            session_id=req.session_id,
            retriever_type=req.retriever_type,
            llm_key=req.llm_key,
            top_k=top_k,
            user_id=current_user["id"],
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Pipeline error: {str(e)}")

    return QueryResponse(
        query=req.query,
        answer=result.get("answer", ""),
        sources=result.get("sources", []),
        retriever_type=req.retriever_type,
        llm_name=result.get("llm_name", req.llm_key),
        latency_total=result.get("latency_seconds", 0.0),
        cost_usd=result.get("cost_usd", 0.0),
        record_id=result.get("record_id", 0),
        retrieved_chunks=result.get("retrieved_chunks", []),
    )


@router.post("/stream")
def query_stream(req: QueryRequest, current_user: dict = Depends(get_current_user)):
    """
    Streaming RAG query via Server-Sent Events.
    Tokens stream as they are generated by the LLM.
    """
    from api.main import get_pipeline

    augmented_query, top_k = _validate_and_augment(req, current_user)

    pipeline = get_pipeline()
    if pipeline is None:
        raise HTTPException(status_code=503, detail="Pipeline not initialized")

    def event_generator():
        try:
            for event in pipeline.stream_rag_query_api(
                query=augmented_query,
                session_id=req.session_id,
                retriever_type=req.retriever_type,
                llm_key=req.llm_key,
                top_k=top_k,
                user_id=current_user["id"],
            ):
                yield f"event: {event['event']}\ndata: {json.dumps(event['data'])}\n\n"
        except Exception as e:
            yield f"event: error\ndata: {json.dumps({'detail': str(e)})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )

